# Generated by Django 4.1.1 on 2022-10-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='user',
        ),
    ]
