# Generated by Django 4.1.1 on 2022-10-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_options_alter_team_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
